
###
# @name tickServer
PUT http://134.117.130.17:3000/searchengines HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "request_url": "http://134.117.135.154:3000"
}

###
# @name getServer
GET http://134.117.130.17:3000/searchengines HTTP/1.1
Content-Type: application/json
Accept: application/json


###
# @name getFruitsServer
GET http://134.117.130.17:3000/fruits?q=apple HTTP/1.1
Content-Type: application/json
Accept: application/json


###
# @name getPersonalServer
GET http://134.117.130.17:3000/personal?q=apple HTTP/1.1
Content-Type: application/json
Accept: application/json