@baseUrl = http://localhost:3000
//we don't need this file for this assignment
<!--
###
# @name listProducts
GET {{baseUrl}}/products HTTP/1.1
Accept: application/json

###
# @name addProduct
# @prompt name
# @prompt price
# @prompt dimensionX
# @prompt dimensionY
# @prompt dimensionZ
# @prompt stock
POST {{baseUrl}}/products HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "{{name}}",
    "price": {{price}},
    "dimensionX": {{dimensionX}},
    "dimensionY": {{dimensionY}},
    "dimensionZ": {{dimensionZ}},
    "stock": {{stock}}
}

###
# @name viewProduct
# @prompt productId
GET {{baseUrl}}/products/{{productId}} HTTP/1.1
Accept: application/json

###
# @name addProductReview
# @prompt productId
# @prompt rating
POST {{baseUrl}}/products/{{productId}}/reviews HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "rating": {{rating}}
}

###
# @name listProductReviews
# @prompt productId
GET {{baseUrl}}/products/{{productId}}/reviews HTTP/1.1
Accept: application/json

###
# @name createOrder
# @prompt username
# @prompt aProductId
# @prompt aQuantity
# @prompt anotherProductId
# @prompt anotherQuantity
POST {{baseUrl}}/orders HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "{{username}}",
    "orderItems": [
        {
            "productId": {{aProductId}},
            "quantity": {{aQuantity}}
        },
        {
            "productId": {{anotherProductId}},
            "quantity": {{anotherQuantity}}
        }
    ]
}

###
# @name listOrders
GET {{baseUrl}}/orders HTTP/1.1
Accept: application/json

###
# @name viewOrder
# @prompt orderId
GET {{baseUrl}}/orders/{{orderId}} HTTP/1.1
Accept: application/json
-->