@baseUrl = http://localhost:3000

###
# @name fruits
# @prompt q
# @prompt boost
# @prompt limit
POST {{baseUrl}}/fruits HTTP/1.1
Content-Type: application/json
Accept: application/json

{    //only adds the values to the payload if they have values
    {{#if q}}"q": {{q}},{{/if}}
    {{#if boost}}"boost": {{boost}},{{/if}}
    {{#if limit}}"limit": {{limit}}{{/if}}
}

###
# @name personal
# @prompt q
# @prompt boost
# @prompt limit
POST {{baseUrl}}/personal HTTP/1.1
Content-Type: application/json
Accept: application/json

{    //only adds the values to the payload if they have values
    {{#if q}}"q": {{q}},{{/if}}
    {{#if boost}}"boost": {{boost}},{{/if}}
    {{#if limit}}"limit": {{limit}}{{/if}}
}